# Generated by Django 3.2 on 2023-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type_property',
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('', 'Estado'), ('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=20),
        ),
    ]
