# Generated by Django 3.2 on 2023-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0002_auto_20230530_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type_property',
            field=models.CharField(choices=[('casa', 'casa'), ('departamento', 'departamento'), ('oficinas', 'oficinas')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
