# Generated by Django 3.2 on 2023-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0005_property_google_maps_url_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
