# Generated by Django 3.2 on 2023-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0007_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
