# Generated by Django 3.2 on 2023-09-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0008_alter_property_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
